name: flutter_front
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # --------------------------------------------------------------
  # External Libraries (라이브러리 추가 시 알파벳 순으로 정렬하세요)
  # --------------------------------------------------------------
  cupertino_icons: ^1.0.8 # iOS 스타일(아이폰)의 기본 아이콘 팩

dev_dependencies:
  # [개발용 의존성] 테스트를 위한 라이브러리
  flutter_test:
    sdk: flutter

  # [개발용 의존성] 코드 스타일 가이드 및 문법 검사(Lint) 도구
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true # 안드로이드 머티리얼 디자인 아이콘 사용 활성화

  # --------------------------------------------------------------
  # Assets & Fonts (추후 필요할 때 주석을 풀고 사용하세요)
  # --------------------------------------------------------------
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700